name: deploy_services
description: Deploy services

inputs:
  environment:
    description: Environment name
    required: true
  stage:
    description: Stage name
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/step/log_blue_green_parameters
      with:
        environment: ${{ inputs.environment }}
        stage: ${{ inputs.stage }}

    - name: "${{ inputs.stage }}: deploy_services"
      shell: bash
      run: |
        echo "Run deploy services for environment: ${{ inputs.environment }}"
        echo "stage: ${{ inputs.stage }}"
