name: setup_blue_green_control
description: Setup blue-green control

inputs:
  environment:
    description: Environment name
    required: true
  stage:
    description: Stage name
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/step/log_blue_green_parameters
      with:
        environment: ${{ inputs.environment }}

    - name: "${{ inputs.stage }}: setup_blue_green_control"
      shell: bash
      run: |
        echo "Run setup blue-green control for environment: ${{ inputs.environment }}"
