name: Log Blue-Green Parameters
description: Logs blue-green deployment variables

runs:
  using: composite
  steps:
    - name: Log blue-green parameters
      shell: bash
      run: |
        echo "Live AKS nodepool: just me yet"
