name: run_health_checks
description: Run health checks

inputs:
  environment:
    description: Environment name
    required: true
  stage:
    description: Stage name
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/step/log_blue_green_parameters
      with:
        environment: ${{ inputs.environment }}
        stage: ${{ inputs.stage }}
   
    - name: "${{ inputs.stage }}: run_health_checks"
      shell: bash
      run: |
        echo "Run health checks for environment: ${{ inputs.environment }}"
        echo "stage: ${{ inputs.stage }}"
