name: deploy_iac
description: Deploy IaC

inputs:
  environment:
    description: Environment name
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/step/log_blue_green_parameters
      with:
        environment: ${{ inputs.environment }}

    - name: Deploy IaC
      shell: bash
      run: |
        echo "Run deploy IaC for environment: ${{ inputs.environment }}"
