name: ECK on AKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prd-eus-001

jobs:
  deploy:
    name: "${{ inputs.environment }} deploy_plan"
    uses: ./.github/workflows/deploy_env_blue_green.yml
    with:
      environment: ${{ inputs.environment }}