on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  health_check:
    name: "${{ inputs.stage }}: health_check"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.3