on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  run_health_check:
    name: "${{ inputs.stage }}: run_health_check"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.3