on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  stage_deploy:
    name: "${{ inputs.environment }}: deploy"
    uses: ./.github/workflows/stage_deploy.yml
    with:
      environment: ${{ inputs.environment }}
      stage: deploy
  
  stage_switch:
    name: "${{ inputs.environment }}: switch"
    needs: stage_deploy
    uses: ./.github/workflows/deploy_services.yml
    with:
      environment: ${{ inputs.environment }}
      stage: switch
  
  stage_health_check:
    name: "${{ inputs.environment }}: health_check"
    needs: stage_switch
    uses: ./.github/workflows/run_health_check.yml
    with:
      environment: ${{ inputs.environment }}
      stage: health_check
  
  stage_destroy:
    name: "${{ inputs.environment }}: destroy"
    needs: stage_health_check
    uses: ./.github/workflows/deploy_iac.yml
    with:
      environment: ${{ inputs.environment }}
      stage: destroy