name: plan_iac
description: Plan IaC

inputs:
  environment:
    description: Environment name
    required: true
  stage:
    description: Stage name
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/step/log_blue_green_parameters
      with:
        environment: ${{ inputs.environment }}

    - name: "${{ inputs.stage }}: plan_iac"
      shell: bash
      run: |
        echo "Run plan IaC for environment: ${{ inputs.environment }}"
