name: Plan IaC
description: Plan IaC

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      
    - uses: ./.github/workflows/reusable/actions/step/log_blue_green_parameters

    - name: Plan IaC
      shell: bash
      run: |
        echo "Run plan IaC"
