name: log_blue_green_parameters
description: Logs blue-green paramters

inputs:
  environment:
    description: Environment name
    required: true
  stage:
    description: Stage name
    required: true

runs:
  using: composite
  steps:
    - name: "${{ inputs.stage }}: log_blue_green_parameters"
      shell: bash
      run: |        
        echo "Environment: ${{ inputs.environment }}"
        echo "Stage: ${{ inputs.stage }}"
        echo "Live AKS nodepool: just me yet"
